import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import {Philosopher} from 'next/font/google';
import {Source_Sans_3} from 'next/font/google';

const philosopher = Philosopher({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-philosopher',
})

const sourceSance3 = Source_Sans_3({
  subsets: ['latin'],
  variable: '--font-sourceSance3'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${philosopher.variable} + ${sourceSance3.variable}`}>{children}</body>
    </html>
  )
}
