import type { Metadata } from 'next'
import './globals.css'
import {Source_Sans_3} from 'next/font/google';

const sourceSance3 = Source_Sans_3({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sourceSance3.className}>{children}</body>
    </html>
  )
}
